# Bonds Prices
## Grupo 600

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from __future__ import division

bonds = pd.read_csv('bonds prices.csv')

In [2]:
bonds.head()

,id,bond_id,trade_price,weight,current_coupon,time_to_maturity,is_callable,reporting_delay,trade_size,trade_type,...,received_time_diff_last1,trade_price_last1,trade_size_last1,trade_type_last1,curve_based_price_last1,received_time_diff_last2,trade_price_last2,trade_size_last2,trade_type_last2,curve_based_price_last2
0,1,1,128.596,11.316404,5.95,26.031126,0,1.731,120000,2,...,758762,129.089,200000,2,129.435587,NaN,NaN,NaN,NaN,NaN
1,2,1,126.673,8.763446,5.95,26.016697,0,30.518,85000,4,...,455028,128.596,120000,2,127.561201,1213791.0,129.089,200000.0,2.0,129.435587
2,3,1,126.880,6.499730,5.95,26.008760,0,4.424,4200000,3,...,250310,126.673,85000,4,126.323528,705339.0,128.596,120000.0,2.0,127.561201
3,4,1,126.362,0.865854,5.95,26.008619,0,43.059,5000001,2,...,4441,126.880,4200000,3,126.761433,254752.0,126.673,85000.0,4.0,126.323528
4,5,1,124.918,11.938543,5.95,25.981840,0,6.332,10000,2,...,844484,126.362,5000001,2,127.025765,848925.0,126.880,4200000.0,3.0,126.761433

## ¿En promedio, qué tiempo de madurez tienen los bonos más caros y los bonos mas baratos?, ¿Qué porcentaje de los bonos baratos tienen un tiempo de madurez mayor a t años?

In [3]:
bonds.trade_price.describe()
#bonos baratos $99.433 o menes (primer cuartil)
#bonos caros $107.11 o más (último cuartil)
low_price = bonds.trade_price < 99.50
high_price = bonds.trade_price > 107.00

In [4]:
bonds.time_to_maturity[low_price].mean()
#los bonos mas baratos tienen un tiempo de madurez promedio de 7.9655 años

7.965532995460775

In [5]:
bonds.time_to_maturity[high_price].mean()
#los bonos mas caros tienen un tiempo de madurez promedio de 8.6504 años

8.65044887413591

In [6]:
allprices = bonds.trade_price.count() #conteo de todos los datos

In [14]:
total = bonds.time_to_maturity.count()
def maturity_time(time):
    less_than_t = bonds.time_to_maturity <= time
    price_count = low_price[less_than_t].count()
    porcentaje = (price_count/total)*100
    return porcentaje

m_time = input("que tiempo de madurez desea? ")
maturity_time(m_time)

que tiempo de madurez desea? 1

6.3430438533693128

In [ ]:
sns.boxplot(x=bonds["trade_type"], y=bonds["trade_price"])
sns.boxplot(x=bonds["trade_type"], y=bonds["time_to_maturity"])

In [9]:
pd.crosstab(index=bonds['trade_price'],columns=bonds['trade_type'], margins=True)

trade_type        2       3       4     All
trade_price
1.009             0       0       1       1
1.04375           0       1       0       1
1.062             1       0       2       3
1.1               2       0       1       3
1.11              1       0       1       2
1.15              2       0       2       4
1.2               2       0       0       2
1.25              2       0       3       5
1.345             1       0       0       1
1.35              1       0       0       1
1.361             0       0       1       1
1.375             6       0       3       9
1.4               0       0       1       1
1.416667          1       0       0       1
1.42              1       0       0       1
1.435             1       0       2       3
1.46125           1       0       0       1
1.5               1       0       6       7
1.5625            0       1       0       1
1.575             1       0       0       1
1.6               0       1       0       1
1.625             0       1       0       1
1.663             0       0       1       1
1.714             1       0       0       1
1.7166            1       0       0       1
1.721             0       0       1       1
1.725             1       1       0       2
1.728             1       0       0       1
1.73              1       0       0       1
1.734             0       0       1       1
...             ...     ...     ...     ...
164.136           0       1       0       1
164.192           2       0       0       2
164.259           1       0       0       1
164.33            0       1       0       1
164.412           0       1       0       1
164.47            1       0       0       1
164.621           1       0       0       1
164.622           0       1       0       1
164.682           0       1       0       1
164.684           0       1       0       1
164.694           0       1       0       1
164.726           0       1       0       1
164.838           0       0       2       2
164.85            0       1       0       1
164.934           0       1       0       1
164.946           0       1       0       1
165.053           0       1       0       1
165.07            0       1       0       1
165.192           0       0       1       1
165.3             0       0       1       1
165.62            0       1       0       1
165.759           0       1       0       1
165.971           1       0       0       1
166.276           1       0       0       1
166.474           0       1       0       1
166.505           0       1       0       1
166.754           0       1       0       1
167.907           0       1       0       1
168.148           0       1       0       1
All          155178  275550  331950  762678

[88870 rows x 4 columns]

In [10]:
pd.crosstab(index=bonds['time_to_maturity'],columns=bonds['trade_type'], margins=True)

trade_type             2       3       4     All
time_to_maturity
0.082471402            1       0       0       1
0.082472079            0       0       1       1
0.082736732            1       0       0       1
0.082736827            0       0       2       2
0.083091902            1       0       0       1
0.085312723            0       0       1       1
0.085312759            0       1       0       1
0.085406241            0       0       1       1
0.085406336            0       1       0       1
0.090999438            0       1       0       1
0.09100046             0       1       0       1
0.091001862            0       1       0       1
0.091003769            0       1       0       1
0.09100473             0       1       0       1
0.091007085            0       1       0       1
0.091009502            0       1       0       1
0.091010929            0       1       0       1
0.091016526            0       0       1       1
0.091426767            0       1       0       1
0.091436999            0       0       1       1
0.091437455            0       0       1       1
0.091437458            1       0       0       1
0.091556626            0       1       0       1
0.096369348            0       1       0       1
0.096369358            1       0       0       1
0.096761173            1       0       1       2
0.098883142            1       0       0       1
0.098938317            0       1       0       1
0.09896088             1       0       0       1
0.098977405            0       1       0       1
...                  ...     ...     ...     ...
84.08022156            0       0       1       1
84.08022528            0       1       0       1
84.08025369            1       0       1       2
84.08037749            0       0       1       1
84.08037754            1       0       0       1
84.08043789            1       0       1       2
84.09960014            0       1       0       1
84.0996005             0       0       1       1
84.0996233             0       1       0       1
84.09962784            0       0       1       1
84.11597343            0       1       0       1
84.11597424            1       0       0       1
84.11868313            0       0       1       1
84.11868316            1       0       0       1
84.11883627            1       0       0       1
84.11883628            1       0       0       1
84.11884733            0       0       1       1
84.1188678             0       1       0       1
84.11889041            0       1       0       1
84.12098936            1       0       0       1
84.12959005            0       1       0       1
84.1295933             0       0       1       1
84.1400841             0       0       1       1
84.14008413            1       0       0       1
84.14064998            1       0       0       1
84.15691738            0       0       1       1
84.1569174             1       0       0       1
84.15949805            1       0       0       1
84.15949848            0       1       0       1
All               155178  275550  331950  762678

[721724 rows x 4 columns]

## ¿Qué porcentaje de los bonos con tasas de interes altas (current_coupon) serán liquidados en, máximo, t años?

In [27]:
bonds.time_to_maturity.describe()
#intereses altos 6.5 o mas

count    762678.000000
mean          6.564305
std           6.267664
min           0.082471
25%           2.493513
50%           4.775924
75%           8.258087
max          84.159498
Name: time_to_maturity, dtype: float64

In [26]:
total_high = bonds.time_to_maturity[bonds.current_coupon >= 6.5]
total_high.count()
#193337 bonos poseen interes mayor que 6.5%

def mttime(time):
    high_this_year = bonds.time_to_maturity[(bonds.current_coupon >= 6.5) & (bonds.time_to_maturity <= time)]
    porc = (high_this_year.count()/total_high.count())*100
    porcb = porc
    return porcb

m_time = input("que tiempo de madurez desea? ")
mttime(m_time)

que tiempo de madurez desea? 1

3.1483885650444563

In [25]:
plt.hist(bonds.time_to_maturity.dropna(),bins=25)

(array([  2.64504000e+05,   2.53081000e+05,   1.55609000e+05,
          1.00300000e+04,   1.96250000e+04,   8.44700000e+03,
          1.42860000e+04,   1.97040000e+04,   1.62630000e+04,
          1.05400000e+03,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          7.50000000e+01]),
 array([  8.24714020e-02,   3.44555249e+00,   6.80863357e+00,
          1.01717147e+01,   1.35347957e+01,   1.68978768e+01,
          2.02609579e+01,   2.36240390e+01,   2.69871201e+01,
          3.03502012e+01,   3.37132822e+01,   3.70763633e+01,
          4.04394444e+01,   4.38025255e+01,   4.71656066e+01,
          5.05286876e+01,   5.38917687e+01,   5.72548498e+01,
          6.06179309e+01,   6.39810120e+01,   6.73440931e+01,
          7.07071741e+01,   7.40702552e+01,   7.74333363e+01,
          8.07964174e+01,   8.41594985e+01]),
 <a list of 25 Patch objects>)

## ¿Qué porcentaje de los volumenes de las últimas dos transacciones han disminuido si se presenta un tiempo de retraso mayor a t segundos?

In [28]:
#ultima transaccion
bonds.trade_size.describe()
#transacciones de gran volumen: 100,000 o más 
big_size = bonds.trade_size >100000
big_size. describe() #762678 transacciones con volumenes mayores a 100,000

#penultima transacción
bonds.trade_size_last1.describe()
#transacciones de gran volumen: 100,000 o más 
old_big_size = bonds.trade_size >100000
old_big_size.describe() #762678 transacciones con volumenes mayores a 100,000

count     762678
unique         2
top        False
freq      582121
Name: trade_size, dtype: object

In [30]:
#ultima transacción 
def delay(dtime):
    big_delay_transactions = (bonds.reporting_delay[(bonds.trade_size >= 100000) & (bonds.reporting_delay <= dtime)]).count()
    return big_delay_transactions

#penúltima transacción   
def old_delay(odtime):
    old_big_delay_transactions = (bonds.reporting_delay[(bonds.trade_size_last1 >= 100000) & (bonds.reporting_delay <= odtime)]).count()
    return old_big_delay_transactions

delayt = input("que tiempo de retraso desea saber? ")
delay(delayt)
old_delay(delayt)

difference = old_delay(delayt)-delay(delayt)
difference/(bonds.reporting_delay.count())*100

que tiempo de retraso desea saber? 20

1.5360348666147443

In [ ]:
sns.boxplot(x=bonds["trade_size"], y=bonds["trade_size_last1"])